# -*- coding: utf-8 -*-
"""image2vector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ombdmI7z-jROrCcjJQJCFl1wFMMwr97z

Image to Vector or Matrix
"""



from PIL import Image
import numpy as np

# Load image
image = Image.open("/content/cat.jpg")

# Convert image to RGB
image = image.convert("RGB")

# Convert image to NumPy matrix
matrix = np.array(image)

print("Image shape:", matrix.shape)
print("Image matrix:")
print(matrix)

# Save matrix as a NumPy file
np.save("image_matrix.npy", matrix)

"""**Vector or Matrix to Image**"""

from PIL import Image
import numpy as np

# # Example grayscale matrix
# matrix = np.array([
#     [0, 50, 100, 150, 200, 255],
#     [50, 100, 150, 200, 255, 200],
#     [100, 150, 200, 255, 200, 150],
#     [150, 200, 255, 200, 150, 100],
#     [200, 255, 200, 150, 100, 50],
#     [255, 200, 150, 100, 50, 0]
# ], dtype=np.uint8)

# Convert matrix to image
image = Image.fromarray(matrix)

# Save image
image.save("output.png")

# Display image
image.show()