# -*- coding: utf-8 -*-
"""Image2Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ag0oTGxxqZhUMSqWYiKhnNbJrwCrXfzS
"""



!pip install transformers torch torchvision pillow huggingface_hub

image_path ="/content/hang-niu-Tn8DLxwuDMA-unsplash.jpg"



import os

HF_TOKEN = "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"
os.environ['HF_TOKEN'] = HF_TOKEN
print("HF_TOKEN defined and set as environment variable.")

import torch
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration
from huggingface_hub import login

# ============================================================
# STEP 1: Hugging Face Login
# ============================================================

# Replace with your Hugging Face token
login("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")


# ============================================================
# STEP 2: Load the BLIP Model
# ============================================================

model_name = "Salesforce/blip-image-captioning-base"

processor = BlipProcessor.from_pretrained(model_name)

model = BlipForConditionalGeneration.from_pretrained(
    model_name
)


# ============================================================
# STEP 3: Select Device
# ============================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

model = model.to(device)

print("Using device:", device)


# ============================================================
# STEP 4: Load Image
# ============================================================

image_path = "/content/dog.jpg"

image = Image.open(image_path).convert("RGB")

print("Image loaded successfully.")


# ============================================================
# STEP 5: Convert Image to Model Input
# ============================================================

inputs = processor(
    images=image,
    return_tensors="pt"
)

# Move inputs to GPU/CPU
inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}


# ============================================================
# STEP 6: Generate Caption
# ============================================================

with torch.no_grad():

    output = model.generate(
        **inputs,
        max_new_tokens=50
    )


# ============================================================
# STEP 7: Convert Output to Text
# ============================================================

caption = processor.decode(
    output[0],
    skip_special_tokens=True
)


# ============================================================
# STEP 8: Display Result
# ============================================================

print("\nImage Caption:")
print(caption)